In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
# From Python lists
x = torch.tensor([1, 2, 3])

print("FROM PYTHON LISTS:", x)
print("TENSOR DATA TYPE:", x.dtype)

FROM PYTHON LISTS: tensor([1, 2, 3])
TENSOR DATA TYPE: torch.int64


In [4]:
# From a NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
torch_tensor_from_numpy = torch.from_numpy(numpy_array)

print("TENSOR FROM NUMPY:\n\n", torch_tensor_from_numpy)

TENSOR FROM NUMPY:

 tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# From Pandas DataFrame
# Read the data from the CSV file into a DataFrame
df = pd.read_csv('./data.csv')

# Extract the data as a NumPy array from the DataFrame
all_values = df.values

# Convert the DataFrame's values to a PyTorch tensor
tensor_from_df = torch.tensor(all_values)

print("ORIGINAL DATAFRAME:\n\n", df)
print("\nRESULTING TENSOR:\n\n", tensor_from_df)
print("\nTENSOR DATA TYPE:", tensor_from_df.dtype)

ORIGINAL DATAFRAME:

    distance_miles  delivery_time_minutes
0            1.60                   7.22
1           13.09                  32.41
2            6.97                  17.47

RESULTING TENSOR:

 tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)

TENSOR DATA TYPE: torch.float64


In [8]:
# All zeros
zeros = torch.zeros(2, 3)

print("TENSOR WITH ZEROS:\n\n", zeros)

TENSOR WITH ZEROS:

 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
# All ones
ones = torch.ones(2, 3)

print("TENSOR WITH ONES:\n\n", ones)

TENSOR WITH ONES:

 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
# Random numbers
random = torch.rand(2, 3)

print("RANDOM TENSOR:\n\n", random)

RANDOM TENSOR:

 tensor([[0.0476, 0.6571, 0.0965],
        [0.6007, 0.5587, 0.4797]])


In [11]:
# Range of numbers
range_tensor = torch.arange(0, 10, step=1)

print("ARANGE TENSOR:", range_tensor)

ARANGE TENSOR: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
# A 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])


In [13]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Add dimension
expanded = x.unsqueeze(0)  # Add dimension at index 0

print("\nTENSOR WITH ADDED DIMENSION AT INDEX 0:\n\n", expanded)
print("\nTENSOR SHAPE:", expanded.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

TENSOR WITH ADDED DIMENSION AT INDEX 0:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

TENSOR SHAPE: torch.Size([1, 2, 3])
